name: quickbooks
description: A package to talk to the quickbook api. Can manage Oauth2 connection and many data queries of the Quickbooks platform.
version: 1.4.0
homepage: https://apollocode.ca/
repository: https://github.com/apollocode-ca/quickbooks

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  alfred: ^1.1.0+2
  collection: ">=1.16.0 <2.0.0"
  http: ">=0.13.0 <=1.1.0"
  intl: ">=0.17.0 <=0.18.1"
  oauth2: ^2.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
